import { USER_ROLE } from './userRoles'
import { PERMISSION } from './permissions'

export const ROLE_PERMISSIONS = {
  [USER_ROLE.ADMIN]: [...Object.values(PERMISSION)],

  [USER_ROLE.SALES]: [
    PERMISSION.ORDER_VIEW,
    PERMISSION.ORDER_CREATE,
    PERMISSION.ORDER_EDIT,
    PERMISSION.ORDER_POST,
    PERMISSION.ORDER_PROCESS,
    PERMISSION.ORDER_CANCEL,

    PERMISSION.CUSTOMER_VIEW,
    PERMISSION.CUSTOMER_CREATE,
    PERMISSION.CUSTOMER_EDIT,

    PERMISSION.PRODUCT_VIEW,
    PERMISSION.PRODUCT_CREATE,
    PERMISSION.PRODUCT_EDIT,
    PERMISSION.PRODUCT_DELETE,
  ],

  [USER_ROLE.OPERATIONS]: [
    PERMISSION.ORDER_VIEW,
    PERMISSION.ORDER_PROCESS,
    PERMISSION.ORDER_COMPLETE,
    PERMISSION.ORDER_CANCEL,

    PERMISSION.CUSTOMER_VIEW,
    PERMISSION.PRODUCT_VIEW,
  ],
}
